//
// Created by hongzhen on 2017/11/24.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "wentsai_hisign_com_testlibrary_TestUtils.h"
#include <android/log.h>
/* Header for class wentsai_hisign_com_testlibrary_TestUtils */
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,"Yu" ,__VA_ARGS__) // 定义LOGI类型
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_wentsai_hisign_com_testlibrary_TestUtils_getName
  (JNIEnv *env, jclass jclas){
        //主函数
        LOGI("Jni测试width： %s", "测试JNI");

  }

#ifdef __cplusplus
}
#endif

