/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wentsai_hisign_com_testlibrary_TestUtils */

#ifndef _Included_wentsai_hisign_com_testlibrary_TestUtils
#define _Included_wentsai_hisign_com_testlibrary_TestUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wentsai_hisign_com_testlibrary_TestUtils
 * Method:    getName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_wentsai_hisign_com_testlibrary_TestUtils_getName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
